apiVersion: v1
data:
  application.yaml: |-
    spring:
      data:
        mongodb:
          uri: mongodb://pay:pay.com@mongo-oipo.database/pay?minPoolSize=10&maxPoolSize=150
kind: ConfigMap
metadata:
  name: mongodb
  namespace: pay
