allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/provisioner: ""
    storageclass.kubernetes.io/is-default-class: "true"
    storageclass.kubesphere.io/supported-access-modes: '["ReadWriteOnce"]'
  name: defa
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: Immediate