apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-account
  name: account
  namespace: pay
  resourceVersion: "24786446"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-account
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-03-25T07:27:43Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-account
    spec:
      affinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/account:1.0.3-k8s
        imagePullPolicy: Always
        name: account
        ports:
        - containerPort: 80
          name: port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-afvxg
        - mountPath: /logs
          name: vol-lqstc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-afvxg
      - hostPath:
          path: /data/logs/account
          type: ""
        name: vol-lqstc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-30T11:41:05Z"
    lastUpdateTime: "2024-03-25T07:27:52Z"
    message: ReplicaSet "account-5fd4b6b87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-03T12:52:26Z"
    lastUpdateTime: "2024-04-03T12:52:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
