apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
  creationTimestamp: "2024-03-14T10:17:55Z"
  generation: 17
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-newglobalpay
  name: channel-newglobalpay
  namespace: pay
  resourceVersion: "24786362"
  uid: 6725ce17-2430-44c2-af13-895360f82e90
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-newglobalpay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-03-29T10:52:00Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-newglobalpay
    spec:
      affinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/channel-newglobalpay:1.0.0-k8s
        imagePullPolicy: Always
        name: channel-newglobalpay
        ports:
        - containerPort: 80
          name: port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-cthck
        - mountPath: /application/channel
          name: vol-vw6mt
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-cthck
      - configMap:
          defaultMode: 420
          name: channel-newglobalpay
        name: vol-vw6mt
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-03-14T10:17:55Z"
    lastUpdateTime: "2024-03-29T10:52:08Z"
    message: ReplicaSet "channel-newglobalpay-7c7c4767c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-03T12:52:21Z"
    lastUpdateTime: "2024-04-03T12:52:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
