apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "23"
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7RWT4/auhf9KqMr/XZJSEKA4F3Vqv0tOhXq0Lfon8WNcwl+49iR7TATIb77kxMgwHRGXby3I87x9T3nHp+wB2zEX2Ss0AoYYNPYyS6BAB6FKoHBB2qk7mpSDgKoyWGJDoHtAZXSDp3QyvrH8oyLHtuCjCJHNhJ6YmgnjsVnEIAu/ibuLLnICB1xdE6Shwl/WFxMiXCWhsV8uQmzMs7DPJ/GYYZ5ni02y3m+yOAQADfUn7wWNVmHdQMM0jidhkkSJrN1MmPxnMWL7xBARYpMDwa2DEBiQbJv+LVGtmi3wKDg2RznRZLiZhrH2TQr+XyR8BzTEtOioJyIx/O0hACetHmUGsuotWQuKp3WLUniTpujvNEoVdhgF/ItKkUydNtWkfX0FNYEDG5eDOu2Qe5fNth5qG2IezaN0ZUhaz8QllIoeiCuVWmBzeM4AEONFBwtsMQ/DAP5v7BOm+6zqIUDlsQBjI3uoUbHt5/Pav3LHH3nzqCjqvPVjZZSqOpbU6Kj4fTnh9ZUnmg6+593Hj5/U7hDIbGQp+VDAK5r/NPXqwJ+nepGnoq97tqRiHthpTRMZ+s4Z9mMZdPvr9hOtVJeuuo/0Ok4YdxshBLO6+Vb0cqhUGQssB97EDX2YiVxlGR5FEfJlC2Xy+XkaYvSe6abXJdmSRRHcfiYe1/1u1etlCstBe+AwTv5hN3Jcr+zYqONG44+d7LSxgHL4/OmEWy001xLYLB+v4LDL29Cq1vDyQ50HJlaqF7ce7LWt4POX8NJSbvJxdtQ6gp+iz+1/lFIggB2WrY13etWHfus/c9TVWz6C+H3T6SuKqFGrjstw9aUtYNDcLNN6speA/Ni+WRfAi/rH7W73legSEo4/PJalMqeu38vW+vIfBTG+sA13mfGvZyL5VsqW0nmy1CzpA220oXndY8h3hrhuvdaOXp2g9KWzE5wese573fcCbevrgtfa/7JIKcVGaHLc9BM45PoZ19sRHWPzfB16Kvc65KAZenoEamrAvnjRepdy7/V9ijqHpqTJdBhP4rJ2WHHGLgpMw7nz5p5NYmvJjaEF7q2v/DnTPp6mbFeE3FMmR97kGjd2qCy4hQfQ8pkYZyEyXwdL1ic9CkT9Nghx97G1YPvffgNJz+Qu/t5wyGcLYtFwed5wX/C3RbtnW05J2s3rZTd3emr0TsNbf+R/kJPY8F358QdOcPatDRqvjrWEKrqpX6Ta7pcJ1M2S9ls+SbXG9zIdfw70rOphRJ1W98dpyCkcF10yeZ+AJyG8wd8Roi/m7rwt4LKT9d/Iwxh2X29/qpePLQ9p/ICcDj8EwAA//9/e+32aQkAAA
    objectset.rio.cattle.io/id: 0b3eea52-b69f-4d08-8830-4a8847f96874
  creationTimestamp: "2024-01-29T19:42:21Z"
  generation: 25
  labels:
    objectset.rio.cattle.io/hash: bc46a6b12af300434dc671c8a2da2bbe8eec062d
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-thunes
  name: channel-thunes
  namespace: pay
  resourceVersion: "27390610"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-thunes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-03-15T10:45:46Z"
        kubesphere.io/restartedAt: "2024-04-08T08:54:51.069Z"
        logging.kubesphere.io/logsidecar-config: '{}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-thunes
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-thunes
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: 172.18.89.0:8083/whales/channel-thunes:1.0.0-k8s
        imagePullPolicy: Always
        name: channel-thunes
        ports:
        - containerPort: 80
          name: thunes
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-urdmt
        - mountPath: /logs
          name: vol-8b9ws
        - mountPath: /application/channel
          name: vol-bai1d
        - mountPath: /data/attachment
          name: volume-hvsnw8
      dnsPolicy: ClusterFirst
      nodeName: prod11.asia-northeast1-a.c.upbeat-arch-379107.internal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-urdmt
      - hostPath:
          path: /data/logs/thunes
          type: ""
        name: vol-8b9ws
      - configMap:
          defaultMode: 420
          name: channel-thunes
        name: vol-bai1d
      - name: volume-hvsnw8
        persistentVolumeClaim:
          claimName: thunes-pv
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-03T12:52:29Z"
    lastUpdateTime: "2024-04-03T12:52:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-07T14:29:20Z"
    lastUpdateTime: "2024-04-08T08:54:59Z"
    message: ReplicaSet "channel-thunes-bcbbd9ff9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 25
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
