apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/6xWT2/buBP9KsEAv5sk64/lyLoVKdrfoSmMxN1D2h7G5FjmhiIFknIiBP7uC0q2JW/jRQ+9mdTwcd7j46PfABvxFxkrtIISsGnsbJ9AAM9CcSjhIzVSdzUpBwHU5JCjQyjfAJXSDp3QyvohP9dFz+2GjCJHNhJ6ZmgvjuA5BKA3fxNzllxkhI4YOifJlwm/2XzDl3MqKKRbysN5muXhpsjykPFFvCzyzXabp3AIgBnqd16LmqzDuoES0jjNwiQJk3yd5GWcltntEwRQkSLTF0OZByBxQ7Jv+FojO7Q7D8eyBBc4T4s04/NNnm/jvMjTdBFTscBlliJfZAXFEMCLNs9SI49aS2aCdJq3JIk5bY7yRqNUYYNdyHaoFMmwYsxzU1gTlDCdHSZtg8x/abDzdbYh5nk0RleGrP1IyKVQ9EhMK26hXMRxAIYaKRhaKBM/GI7i/8I6bbovohYOyiQOYGzxDWp0bPflrNOfZOfbdgYdVZ2HNlpKoapvDUdHw9avj62pPMs0/583HL5+U7hHIXEjT9OHAFzX+NHDBYCfp7qRJ7DrZh1ZuF8clIZpvo6Lcp6X8+zpittUK+XUTH9apOPZ4nYrlHBeLN+HVg6FImOh/P4GosZeqSSOknkRxVGSlcvlcjl72aH0bulmE9wyieIoDp8LC8GwdNVKudJSsA5K+CBfsLNwxX6NNm7Y9NzDShsHZRGfVxwrjXaaaQklrO9WcPjpXWd1axjZgYUjUwvVC3pP1vpG0PkbN+O0n02+hlJX8G79qelPQhIEsNeyrelet+rYZO1/nlCx6W+AXz+TuqqEGlnutQxVUcXeO/+x7CjG5Tqrbs0CDj89Ra7suak72VpH5pMw1kem8ZYx7lehLdsRbyWZrwMmpy220oXneV9DrDXCdXdaOXp1g4CWzF4w+sCY73dcCf/+dAl8KeVng4xWZITm58DI4pOW57PeiuoemyHfe5R7zQnKeTqeu9TVBtnzJLouVf09lPdD8ELnIT3Qtf2NO4fCwzThPBNxvObf30CidWuDyorT/b3+UPjaIUgu6iZxkC+f+jewN6FPn2HnR3I3P6YEwttFXhQ5z/niB9zs0N7YljGydttK2d2cApt41PsDbf84fqWXEfDDOfJGzrA2rR8fs291hBGq6nW+xnUexkmYLtdJVubpkcN7XN+rG7mOfwN6QrVQom7rm+MpCClcd8Hmfig4Hc5v8BlL/I3SG+9l4p8vn29DyLuHyzdtMmh7TnxScDj8EwAA//9ZjhDk4QgAAA
    objectset.rio.cattle.io/id: 4bd94e8e-e7e5-4235-b835-cd60985bff52
  creationTimestamp: "2024-01-29T19:40:15Z"
  generation: 4
  labels:
    objectset.rio.cattle.io/hash: 2c31a6a42823d4b55f05852260e86a932ad638e0
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-gcc
  name: channel-gcc
  namespace: pay
  resourceVersion: "16976544"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-gcc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-01-29T21:20:22Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-gcc
    spec:
      affinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/channel-gcc:1.0.0-k8s
        imagePullPolicy: Always
        name: channel-gcc
        ports:
        - containerPort: 80
          name: gcc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-n8g0e
        - mountPath: /application/channel
          name: vol-sn7r6
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-n8g0e
      - configMap:
          defaultMode: 420
          name: channel-gcc
        name: vol-sn7r6
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-29T20:37:05Z"
    lastUpdateTime: "2024-01-29T21:20:35Z"
    message: ReplicaSet "channel-gcc-dc6dd4895" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-03-15T11:05:34Z"
    lastUpdateTime: "2024-03-15T11:05:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
