apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
  creationTimestamp: "2024-03-04T08:49:21Z"
  generation: 15
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-cadopay
  name: channel-cadopay
  namespace: pay
  resourceVersion: "16976350"
  uid: b47eeb6f-dcc2-48b2-aeb4-e3f10cd4fcba
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-cadopay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-03-13T13:08:23Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-cadopay
    spec:
      affinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/channel-cadopay:1.0.0-k8s
        imagePullPolicy: Always
        name: channel-cadopay
        ports:
        - containerPort: 80
          name: pppp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-1yqyd
        - mountPath: /application/channel
          name: vol-lkjdx
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-1yqyd
      - configMap:
          defaultMode: 420
          name: channel-cadopay
        name: vol-lkjdx
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-03-04T08:49:21Z"
    lastUpdateTime: "2024-03-13T13:08:27Z"
    message: ReplicaSet "channel-cadopay-57559658cc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-03-15T11:05:06Z"
    lastUpdateTime: "2024-03-15T11:05:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
