apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
  creationTimestamp: "2024-03-01T07:50:19Z"
  generation: 13
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-oepay
  name: channel-oepay
  namespace: pay
  resourceVersion: "24786435"
  uid: 5b01300a-de8e-450f-9622-71e4b968398a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-oepay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-03-24T11:59:41Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-oepay
    spec:
      affinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/channel-oepay:1.0.0-k8s
        imagePullPolicy: Always
        name: channel-oepay
        ports:
        - containerPort: 80
          name: port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-3gieg
        - mountPath: /application/channel
          name: vol-hdelo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-3gieg
      - configMap:
          defaultMode: 420
          name: channel-oepay
        name: vol-hdelo
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-03-01T07:50:20Z"
    lastUpdateTime: "2024-03-24T11:59:49Z"
    message: ReplicaSet "channel-oepay-846ffbd4f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-03T12:52:26Z"
    lastUpdateTime: "2024-04-03T12:52:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
