apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    objectset.rio.cattle.io/hash: 4f1f4b9352ec99e898576528dfc357f707fba166
    workload.user.cattle.io/workloadselector: apps.deployment-pay-console
  name: console
  namespace: pay
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-03-25T07:25:56Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-console
    spec:
      affinity: {}
      containers:
      - image: 172.18.89.0:8083/whales/console:1.0.0
        imagePullPolicy: Always
        name: console
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /logs
          name: vol-zzi5q
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/logs/console
          type: ""
        name: vol-zzi5q
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-29T20:37:05Z"
    lastUpdateTime: "2024-03-25T07:26:08Z"
    message: ReplicaSet "console-589fff5db9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-03T12:52:28Z"
    lastUpdateTime: "2024-04-03T12:52:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
