kind: Deployment
apiVersion: apps/v1
metadata:
  name: core
  namespace: pay
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-core
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-core
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-core
    spec:
      volumes:
        - name: vol-votbv
          configMap:
            name: logback
            defaultMode: 420
        - name: vol-kopks
          hostPath:
            path: /data/logs/core
            type: ''
        - name: vol-b3vhk
          configMap:
            name: core
            defaultMode: 420
        - name: volume-iwa0fi
          persistentVolumeClaim:
            claimName: thunes-pv
      containers:
        - name: core
          image: '172.18.89.0:8083/whales/core:1.0.2-k8s'
          ports:
            - name: core
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: vol-votbv
              mountPath: /application/loggin
            - name: vol-kopks
              mountPath: /logs
            - name: vol-b3vhk
              mountPath: /application/core
            - name: volume-iwa0fi
              mountPath: /data/attachment
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
