apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-devops-jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-devops-jenkins
    spec:
      affinity: {}
      containers:
      - image: jenkins/jenkins:latest
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8082
          hostPort: 8082
          name: port1
          protocol: TCP
        - containerPort: 50000
          hostPort: 50000
          name: port2
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: vol-izqtk
        - mountPath: /var/run/docker.sock
          name: vol-o58tt
        - mountPath: /usr/bin/docker
          name: vol-h8hxt
        - mountPath: /data/project
          name: vol-oq9hx
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/jenkins
          type: ""
        name: vol-izqtk
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: vol-o58tt
      - hostPath:
          path: /usr/bin/docker
          type: ""
        name: vol-h8hxt
      - hostPath:
          path: /data/project
          type: ""
        name: vol-oq9hx
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
