apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "38"
  creationTimestamp: "2024-01-29T23:24:41Z"
  generation: 38
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-merchant
  name: merchant
  namespace: pay
  resourceVersion: "28364426"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-merchant
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-04-10T04:20:01Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-merchant
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/merchant:1.0.0
        imagePullPolicy: Always
        name: merchant
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/reportFiles
          name: report-files
        - mountPath: /application/files
          name: files
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/project/merchant/reportFiles
          type: ""
        name: report-files
      - hostPath:
          path: /data/project/merchant/files
          type: ""
        name: files
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-03T12:52:21Z"
    lastUpdateTime: "2024-04-03T12:52:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-29T23:24:41Z"
    lastUpdateTime: "2024-04-10T04:20:11Z"
    message: ReplicaSet "merchant-9cd7f79f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 38
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
