apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: "2024-03-27T09:43:14Z"
  generation: 10
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-whalespaybot
  name: whalespaybot
  namespace: pay
  resourceVersion: "26787842"
  uid: 33e2f480-9bfb-4f09-a57e-93b210aac431
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pay-whalespaybot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubesphere.io/restartedAt: "2024-04-07T06:06:37.663Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-pay-whalespaybot
    spec:
      affinity: {}
      containers:
      - image: 10.148.0.13:9999/whalespay/whalespaybot:1.0.1-k8s
        imagePullPolicy: Always
        name: whalespaybot
        ports:
        - containerPort: 80
          name: prot
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /application/loggin
          name: vol-uruob
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logback
        name: vol-uruob
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-03T12:52:27Z"
    lastUpdateTime: "2024-04-03T12:52:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-03-27T09:57:26Z"
    lastUpdateTime: "2024-04-07T06:06:45Z"
    message: ReplicaSet "whalespaybot-699c84cf55" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
