apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/assets-server"]'
    management.cattle.io/ui-managed: "true"
  name: assets-server
  namespace: pay
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port1
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-assets-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
