apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["assets-server/attachment"]'
    management.cattle.io/ui-managed: "true"
  name: attachment
  namespace: assets-server
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: attachment
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: attachment
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-assets-server-attachment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
