apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/channel-vt"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-02-04T08:55:37Z"
  name: channel-vt
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: channel-vt
    uid: 8337f907-fb30-4a29-8a89-89d95a436601
  resourceVersion: "2079175"
  uid: d36d5012-25c5-4bbf-baeb-54fdc2d182c3
spec:
  clusterIP: 10.96.0.78
  clusterIPs:
  - 10.96.0.78
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: vt
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-vt
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
