apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/channel-oepay"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-03-01T07:50:20Z"
  name: channel-oepay
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: channel-oepay
    uid: 5b01300a-de8e-450f-9622-71e4b968398a
  resourceVersion: "11723350"
  uid: 8110a98a-daa9-4865-81f9-32e6efdec4e0
spec:
  clusterIP: 10.96.0.186
  clusterIPs:
  - 10.96.0.186
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-oepay
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
