apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/channel-newglobalpay"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-03-14T10:17:55Z"
  name: channel-newglobalpay
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: channel-newglobalpay
    uid: 6725ce17-2430-44c2-af13-895360f82e90
  resourceVersion: "16589956"
  uid: 33ea912d-6d3b-4744-a573-4f90f30d8228
spec:
  clusterIP: 10.96.1.76
  clusterIPs:
  - 10.96.1.76
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-newglobalpay
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
