apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/channel-dwidepay"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-01-29T21:27:20Z"
  name: channel-dwidepay
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: channel-dwidepay
    uid: 1569cfe0-4a30-4b64-bed3-293f6ae71389
  resourceVersion: "37863"
  uid: f37fbcd7-21ee-4666-8d57-38a866ce30e0
spec:
  clusterIP: 10.96.2.226
  clusterIPs:
  - 10.96.2.226
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: myport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-channel-dwidepay
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
