apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/console"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-01-29T21:37:22Z"
  name: console
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: console
    uid: 24d1facb-4908-4bf2-b43a-cb47400b92f6
  resourceVersion: "40690"
  uid: 6deefb7a-22bd-43ac-81b5-8a2a906fcdc4
spec:
  clusterIP: 10.96.3.63
  clusterIPs:
  - 10.96.3.63
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-console
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
