apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/merchant"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-01-29T23:28:50Z"
  name: merchant
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: merchant
    uid: 82133f7a-25fb-45ee-b5fa-d8d324452890
  resourceVersion: "70708"
  uid: aea0bfcb-8e84-448f-8820-98a08232be79
spec:
  clusterIP: 10.96.3.134
  clusterIPs:
  - 10.96.3.134
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-merchant
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
