apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["database/mongo-2"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2024-03-22T07:40:03Z"
  name: mongo-2
  namespace: database
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: mongo-2
    uid: 03b57d96-70d8-452e-868a-6244ac5c3af8
  resourceVersion: "19701620"
  uid: 4aadbe15-a38a-404c-aefd-8f364814d4fe
spec:
  clusterIP: 10.96.3.232
  clusterIPs:
  - 10.96.3.232
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-database-mongo-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
