apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["database/rabbitmq"]'
    management.cattle.io/ui-managed: "true"
  name: rabbitmq
  namespace: database
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: rabbitmq
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http5672
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: http15672
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-database-rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
