apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["database/redis"]'
    management.cattle.io/ui-managed: "true"
  name: redis
  namespace: database
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: redis
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-database-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
