apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["pay/settle"]'
    management.cattle.io/ui-managed: "true"
  name: settle
  namespace: pay
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: settle
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-pay-settle
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


